### ISSUE TITLE
gh-pages images

### ISSUE THREAD

**Issue by kbeflo** [kbeflo/evilportals#11]
![screenshot_20171226-160324](https://user-images.githubusercontent.com/13497504/34363974-1b5e5f1e-eabc-11e7-99f5-78043f8b3ac9.png)
![screenshot_20171226-165417](https://user-images.githubusercontent.com/13497504/34363975-1d4b32ca-eabc-11e7-8532-2105a160c5c1.png)
![screenshot_20171226-165812](https://user-images.githubusercontent.com/13497504/34363977-1e8f4ca2-eabc-11e7-885e-e7dbd845e217.png)
![screenshot_20171226-165904](https://user-images.githubusercontent.com/13497504/34363979-1f66e108-eabc-11e7-8dbb-39fa8b22c3a7.png)
![screenshot_20171226-171539](https://user-images.githubusercontent.com/13497504/34363982-20258324-eabc-11e7-93e0-b775fa1bcc25.png)

**Comment by kbeflo** [comment]
![Screenshot_20200726-135116_CaptivePortalLogin](https://user-images.githubusercontent.com/13497504/88472836-bc7b9780-cf49-11ea-986e-9ff6c05abc01.png)

**Comment by kbeflo** [comment]
![Screen Shot 2020-07-26 at 15 38 46](https://user-images.githubusercontent.com/13497504/88474126-4f223380-cf56-11ea-97fa-64c3e8fdf514.png)

**Comment by JediMasterX** [comment]
seems like the pages needs an update for some 2020 flavor.. can you provide us with new and upgraded templates?
my pineapple is useless, but for your work - Thanks.
JMX

**Comment by kbeflo** [comment]
![Screenshot_20201113-172033_CaptivePortalLogin](https://user-images.githubusercontent.com/13497504/99057411-b849b780-25d6-11eb-8e88-5e4d7dd32ee6.png)

**Comment by kbeflo** [comment]
![Screenshot_20201113-223544_CaptivePortalLogin](https://user-images.githubusercontent.com/13497504/99083728-e643f180-2600-11eb-95b0-9d181001863b.png)
