### ISSUE TITLE
portal login file not found

### ISSUE THREAD

**Issue by ChrisCodes94** [kbeflo/evilportals#18]
I am having trouble copying the portals 
After I submit my password it says 

root@kali:~/evilportals/portals# scp -r portal-login root@172.16.42.1:/root/portals/
root@172.16.42.1's password: 
portal-login: No such file or directory

EvilportalsNano

Am I missing a file or has the "portal-login" file been removed?

Development branch of the Evil Portal has been installed (v3.1)
Pineapple(v2.2.0)
Linux kali 4.13.0

**Comment by kbeflo** [comment]
The "portal-login" is just a placeholder for the portal you want to use. You can choose which one from here [portals](https://github.com/kbeflo/evilportals/tree/master/portals)

**Comment by ChrisCodes94** [comment]
Thanks mate
