### ISSUE TITLE
optimumwifi

### ISSUE THREAD

**Issue by mjnohai** [kbeflo/evilportals#19]
Would love to see one for optimumwifi 👍

**Comment by H4xl0r** [comment]
we need some source files or a link to a portal page at least.

**Comment by kbeflo** [comment]
@H4xl0r come by my discord server

**Comment by H4xl0r** [comment]
> @H4xl0r come by my discord server

LinK?

**Comment by mjnohai** [comment]
https://cablewifi.optimum.net/signin.jsp?mso=cvc

**Comment by kbeflo** [comment]
https://discordapp.com/invite/C43625u

**Comment by H4xl0r** [comment]
> https://cablewifi.optimum.net/signin.jsp?mso=cvc

perfect thanks , will see what i can do :)

**Comment by H4xl0r** [comment]
#22  Is including the optimum wifi portal 
can be closed
