### ISSUE TITLE
Redirecting/HTTPS

### ISSUE THREAD

**Issue by MinmotoMusashi** [kbeflo/evilportals#20]
When creating a new portal. At the top of the index.php script where it's parsing the requested URL.

It's currently:
$destination = "http://" . $_SERVER['HTTP_HOST'] . $_SERVER['HTTP_URI'] . "";
And should be:
$destination = "http://" . $_SERVER['HTTP_HOST'] . $_SERVER['REQUEST_URI'];
And this would allow http or https:
$destination = (isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] === 'on' ? "https" : "http") . "://$_SERVER[HTTP_HOST]$_SERVER[REQUEST_URI]";

Also redirecting doesn't work. What function starts handleAuthorization? onSuccess() is working, but
redirect() isn't.

In MyPortal script your notes say that we can put in what we want, but the redirect() function is
inside the protected handleAuthorization.

Maybe leaving redirect inside the public function in the myportal script?

**Comment by H4xl0r** [comment]
Pulled the Fix is included now.

Can be closed. Thanks for sharing :+1:
