### ISSUE TITLE
Request Login Template Here !

### ISSUE THREAD

**Issue by H4xl0r** [kbeflo/evilportals#23]
Hey People ,

If you are missing some Portals / Logins , let us know !.
The Best way is to request them here and give some links as example eg. the login page.

i will see what i can do with that info.
Would like to see this growing and evolving.

And if you have any hints ... 
Thanks

IF YOU WANT TO SUPPORT US , GO OUT AND SEARCH FOR PUBLIC HOTSPOTS.
THE MORE THAN BETTER ! 

Connect to the Public Wifi (with portal).
Get the IP info of the Router eg. Portal Page. (This shouldn't be too much hussle. mostly the page will pop up direktly and you can see the ip.)
then use a tool like httrack https://www.httrack.com/ to save the page and its content to an folder on your Harddrive.
SEND US THESE TEMPLATES, I CAN TRANSFORM THEM MOST TIMES!

**Comment by zerocolTHS** [comment]
Don't suppose this issue was fixed before it was closed? 
https://github.com/kbeflo/evilportals/issues/9

**Comment by H4xl0r** [comment]
This issue is your template issue ! the examples should work (not working without entering things!)
Check the pulls

**Comment by zerocolTHS** [comment]
The templates used are form this github so clearly that's not my issue. 

I will download and try again.

**Comment by kbeflo** [comment]
@H4xl0r we need to discuss the details of mailtoken and newsletter.

**Comment by H4xl0r** [comment]
Let me know how i can help , i was many times on your chat but no response 
the mailtoken funktion is only working with my version of evilportal ,they dont take the pull request 
then you need to enable smtp settings via reporting topic on the pinapple

**Comment by kbeflo** [comment]
@H4xl0r consider that some people have day jobs and too tired so they can't respond all the time. You can still continue on your fork and I will gladly review your changes and pull them. I'll still be on my Discord server, please note I'm on GMT+8.

**Comment by H4xl0r** [comment]
ok its the time delay , i wont say anything against working , do the same , but its a hobby also, so why not working on it to have fun ... 
the GMT+8 is the problem i think ...

we have to wait till evilportal takes the pull 

then i will pull you more portals 
some token portals / newsletter 
and some Hotel portals (im on holiday and all hotel are using Portals here) so yay thanks for that :-) 
no stress

**Comment by jubsie** [comment]
How about an iCloud login? To go with the Google one.

**Comment by H4xl0r** [comment]
https://phishingpage.org/product/icloud-phishing-page-mobile-responsive/ 
im a bit busy at the moment but will see what i can do in future, thanks for the request by the way :-)

**Comment by kbeflo** [comment]
@H4xl0r I'd rather not have you advertising third party shops for the pages. Keep everything open source under GPL3

**Comment by H4xl0r** [comment]
sry

**Comment by kbeflo** [comment]
Glad to hear about the new Google login. I've been tweaking the google portal and still haven't merged it on the master branch yet. 

Also looking to update the Facebook login. Copying the portal on m.facebook.com.

**Comment by H4xl0r** [comment]
please merge ! :-) @kbeflo

**Comment by kbeflo** [comment]
You can just switch branch and then pull from there.
