### ISSUE TITLE
Contributing Pages + wifi-connect page porting

### ISSUE THREAD

**Issue by kn0wledge** [kbeflo/evilportals#3]
hi @kbeflo, 

I think the potential of evil portal is amazing with quality pages like yours. Unfortunately I don't know how to code yet, but I can def learn how to edit existing pages . I've already ported 2 pages from fluxion to work with Nano, would like to contribute it to your repository but I'm not sure how :P please let me know how i can do it.. i would just upload the folder as is and you can test it .

On another note, I tried porting the wifi-connect page of wifiphisher and got halfway but stuck as I am not able to get the pop-out to work: link to actual page: [https://github.com/wifiphisher/wifiphisher/tree/master/wifiphisher/data/phishing-pages/wifi_connect](url) 

first port (on old version): [https://github.com/kn0wledge/Evilportal-wifi-connect](url)

the old one works but has scaling issues on PC and Mac and does not have a pop out for android and ios.. can we partner on making this one work? and anyway of keeping the automation of detecting the essid that serve them with the same essid name during the password prompt? 

thanks man

**Comment by kbeflo** [comment]
Awesome work, I'll test it out and find out what's wrong with it. Also I invite you come to hak5.org irc.

**Comment by kbeflo** [comment]
I got it working, it could use some adjustments

**Comment by kn0wledge** [comment]
@kbeflo yeah try the page on the first link, it has the pop out functionality and a better recognition of devices.. i tried porting the new version but i could not get the pop out to work. .. can't get irc to work . got jabber?

**Comment by kn0wledge** [comment]
when you will have the time , I tried to create my own site clones of linkedin and some other sites, some i was able to get them to work with EP but others it just does not want to work.. im pretty sure my issue is in the MyPortal.php... i can share these pages with you and you can take a quick look. they are 90% done... just a minor thing doesnt allow it to work .


below is a fully working page : you can add it to your templates or teach me how to add it to your rep. 
[Upgrade-TP-link.zip](https://github.com/kbeflo/evilportal-templates/files/818891/Upgrade-TP-link.zip)

This one, I can't get the capture ... not sure why though 
[linkedin.zip](https://github.com/kbeflo/evilportal-templates/files/818893/linkedin.zip)

also, does the onsubmit have to always return : "you have not been authorized"? how can we change that and either redirect to another page, or just decide not to authorize and not give them internet ..etc

gotta go for now, will check for replies later

**Comment by kn0wledge** [comment]
@kbeflo , any luck ?

**Comment by kbeflo** [comment]
@kn0wledge i modified the template for wifi pineapple evilportal 2.9 beta compatibility, tested it out on an android device, no input dialog, i installed the latest wifiphisher on a rpi 3 and tested on the same device and input dialog works fine. 

for now i suggest we could create a simple template without os detection to avoid any issue, target only a specific device for each template.

**Comment by kn0wledge** [comment]
@kbeflo fair enough, do you think we should check with the dev. of evil portal on hak5 on why that would be? also.. what is the difference between 2.9 beta and the current official release? worth the move? 

also did you take a look at the linkedin file i shared? what am I doing wrong? thx man

**Comment by kbeflo** [comment]
Have you tried using wifiphisher/extra-phishing-pages, the device-modal works very good for android and ios devices. 

Ergo you should try capturing post from the device-modal template. 

I have recently tried, but failed capturing post for the Pineapple.
