### ISSUE TITLE
For some reason not working for me.

### ISSUE THREAD

**Issue by BigBankElit3** [kbeflo/evilportals#4]
I tried them all and when i check preview after i hit "activate" and "start" i hit "live preview" and it shows as "403 forbidden nginx/1.4.7"
<img width="1440" alt="screen shot 2017-04-13 at 10 45 37 pm" src="https://cloud.githubusercontent.com/assets/25236476/25031456/06551c5c-209b-11e7-89de-c1a938fc86ea.png">
<img width="1440" alt="screen shot 2017-04-13 at 10 45 43 pm" src="https://cloud.githubusercontent.com/assets/25236476/25031460/0c0c0548-209b-11e7-85a6-430f5a1e93ff.png">

**Comment by kbeflo** [comment]
You are using Evil Portal 2.0, use Evil Portal 2.9 manual installation instructions can be found [here](https://github.com/frozenjava/EvilPortalNano/tree/development), as it is not available on the Pineapple bar.

**Comment by BigBankElit3** [comment]
thanks ill try that

**Comment by BigBankElit3** [comment]
still no luck 


<img width="1440" alt="screen shot 2017-04-14 at 11 49 30 am" src="https://cloud.githubusercontent.com/assets/25236476/25048219/3f072144-2109-11e7-9621-773c1d9a50d5.png">
<img width="1440" alt="screen shot 2017-04-14 at 11 49 11 am" src="https://cloud.githubusercontent.com/assets/25236476/25048220/3f4ad7e0-2109-11e7-9fea-ef95b965b5df.png">
<img width="1440" alt="screen shot 2017-04-14 at 11 49 02 am" src="https://cloud.githubusercontent.com/assets/25236476/25048221/3fc02d2e-2109-11e7-9cc3-c197c48ab0e0.png">

**Comment by BigBankElit3** [comment]
All good now it was my connection but now I see it working in live preview but when I connect to pineapple it doesn't pop up it still lets me browse freely
